version: "3"
services:
    influxdb:
        image: influxdb:latest
        volumes:
            - influxdb_data:/var/lib/influxdb
        ports:
            - 0.0.0.0:8086:8086
        restart: always
        environment:
            INFLUXDB_DB: "netmetrics"
            INFLUXDB_ADMIN_USER: admin
            INFLUXDB_ADMIN_PASSWORD: admin

    chronograf:
        image: chronograf:latest
        volumes:
            - chronograf_data:/var/lib/chronograf
        ports:
            - 0.0.0.0:8888:8888
        restart: always

volumes:
    influxdb_data:
    chronograf_data: