name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: |
          git clone https://github.com/jrcichra/gh-actions-telegraf
          bash gh-actions-telegraf/telegraf.sh
          sudo apt install -y libpcap-dev
          mkdir builds/
          bash -x build_all.sh
        env:
          INFLUX_URL: ${{ secrets.INFLUX_URL }}
          INFLUX_USERNAME: ${{ secrets.INFLUX_USERNAME }}
          INFLUX_PASSWORD: ${{ secrets.INFLUX_PASSWORD }}
      - name: Release
        uses: ncipollo/release-action@v1.6.1
        with:
          tag: ${{ github.run_number }}
          artifacts: "builds/*"
          allowUpdates: "true"
          token: ${{ secrets.GITHUB_TOKEN }}
